project:
  type: website
  output-dir: _site

website:
  title: "DAI — Développement d'applications internet"
  page-navigation: true
  search: true
  sidebar:
    style: docked
    logo: assets/heig-vd.svg
    contents:
      - index.qmd
      - section: "Chapters"
        contents:
          - chapters/00-environment-setup.qmd
          - chapters/05-docker.qmd
      - section: "Practical work"
        contents:
          - practical-work/pw1.qmd
          - practical-work/pw2.qmd
          - practical-work/pw3.qmd

format:
  html:
    theme: [litera, assets/dai.scss]
    lightbox: true
    toc: true
    toc-depth: 3
    code-copy: true
    link-external-newwindow: true
